### ISSUE TITLE
likely a bug in "apply_rotary_pos_emb_torch"

### ISSUE THREAD

**Issue by ruowenWu** [kroggen/tokenformer-minimal#1]
Hi, thank you for your minimal implementation that make tokenformer approachable. 

In the function `apply_rotary_pos_emb_torch` of `positional_embeddings.py`, I found a probable error during my runs of the code that may lead to my running errors:

```python
# line 100
cos, sin = (
        cos[offset : q.shape[0] + offset, ...],
        sin[offset : q.shape[0] + offset, ...],
    )
```

`q` is of shape `[bsz, seq_len, num_head, hsz_per_head]` and `cos` is of shape `[seq_len, 1, 1, hsz_per_head]` (given by `cos_cached = emb.cos()[:, None, None, :]` in `RotaryEmbedding._prepare_cache`) before this piece of code. 
It seems the slicing here leads to shape mismatch because the result shape of `cos` is `[bsz, 1, 1, hsz_per_head]` if bsz < seq_len. When it comes to `(q * cos)` in `return (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)`, the shape mismatch error is raised.

**Comment by kroggen** [comment]
It is strange because it works perfectly for me

Are you following the usage instructions on the README?

Which model have you downloaded?

Are you using the example command line there as a test?

Which version of pytorch are you using?

Have you tried the tinygrad implementation? (check the other branch) Does it work for you?

**Comment by ruowenWu** [comment]
pytorch version: 2.0.1+cu118
transformers version: 4.39.1

I tried only the pytorch version and trained from scratch. For simplicity of intergrating Pattention into my pytorch project, I kept only codes necessary to call `class TokenFormerBlock` in `tokenformer_minimal.py` and removed others. The shape mismatch occurred when I training with my own data and a batch size of 200.  

Because it seems to be an implementation problem of rotational position embedding, I compared the implementation with Huggingface `transformers.models.llama.modeling_llama.LlamaRotaryEmbedding`. Then I figured out a solution by only modifying `RotaryEmbedding._prepare_cache(...)` and `apply_rotary_pos_emb_torch(...)` in `positional_embeddings.py`, which seems more consistent the implementaion of `LlamaRotaryEmbedding` also:

Step1: `# [:, None, None,:] --> [:, None, :]` in `RotaryEmbedding._prepare_cache(...)`

```
# Original
cos_cached = emb.cos()[:, None, None, :]
sin_cached = emb.cos()[:, None, None, :]
# emb.shape: (max_seq_len, hsz_per_head)
# cos_cached.shape: (max_seq_len, 1, 1, hsz_per_head)
# sin_cached.shape: (max_seq_len, 1, 1, hsz_per_head)
```

```
# Now
cos_cached = emb.cos()[:, None, :]
sin_cached = emb.cos()[:, None, :]
# emb.shape: (max_seq_len, hsz_per_head)
# cos_cached.shape: (max_seq_len, 1, hsz_per_head)
# sin_cached.shape: (max_seq_len, 1, hsz_per_head)
```

Step2: `# q.shape[0] --> q.shape[1]` in `apply_rotary_pos_emb_torch(...)`

```
# Original
cos, sin = (
        cos[offset: q.shape[0] + offset, ...],
        sin[offset: q.shape[0] + offset, ...],
    )
# input shape of q: (bsz, seq_len, num_head, hsz_per_head)
# input shape of cos: (max_seq_len, 1, 1, hsz_per_head) # sorry for the typo (seq_len, 1, 1, hsz_per_head) in the earlier post.
# result shape of cos: (bsz, 1, 1, hsz_per_head) # not sure why offseting with batch size but make sense if offseting seq_len.

# Then q*cos: (bsz, seq_len, num_head, hsz_per_head) * (bsz, 1, 1, hsz_per_head) --> Error: shape mismatch.
```

```
# Now
cos, sin = (
        cos[offset: q.shape[1] + offset, ...],
        sin[offset: q.shape[1] + offset, ...],
    )
# input shape of q: (bsz, seq_len, num_head, hsz_per_head)
# input shape of cos: (max_seq_len, 1, 1, hsz_per_head)
# result shape of cos: (seq_len, 1, 1, hsz_per_head)

# Then q*cos: (bsz, seq_len, num_head, hsz_per_head) * (seq_len, 1, 1, hsz_per_head) --> (bsz, seq_len, num_head, hsz_per_head)
```

---
FYI
In `transformers.models.llama.modeling_llama.LlamaRotaryEmbedding`, cos_cached is created with a shape of `(max_seq_len, hsz_per_head)`:
```
class LlamaRotaryEmbedding(nn.Module):
    def __init__(self, dim, max_position_embeddings=2048, base=10000, device=None, scaling_factor=1.0):
        super().__init__()
        self.scaling_factor = scaling_factor
        self.dim = dim
        self.max_position_embeddings = max_position_embeddings
        self.base = base
        inv_freq = 1.0 / (self.base ** (torch.arange(0, self.dim, 2, dtype=torch.int64).float().to(device) / self.dim))
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        # For BC we register cos and sin cached
        self.max_seq_len_cached = max_position_embeddings
        t = torch.arange(self.max_seq_len_cached, device=device, dtype=torch.int64).type_as(self.inv_freq)
        t = t / self.scaling_factor
        freqs = torch.outer(t, self.inv_freq)
        # Different from paper, but it uses a different permutation in order to obtain the same calculation
        emb = torch.cat((freqs, freqs), dim=-1)
        self.register_buffer("_cos_cached", emb.cos().to(torch.get_default_dtype()), persistent=False)
        self.register_buffer("_sin_cached", emb.sin().to(torch.get_default_dtype()), persistent=False)
```


In `transformers.models.llama.modeling_llama.apply_rotary_pos_emb(...)`, `cos_cached` is reshaped to a shape of `(max_seq_len, 1, hsz_per_head)` from `(max_seq_len, hsz_per_head)` by default, which is not the same as `(max_seq_len, 1, 1, hsz_per_head)` in the original code but is followed in the solution code:

```
def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    cos = cos.unsqueeze(unsqueeze_dim)  # Here: (max_seq_len, hsz_per_head) --> (max_seq_len, 1, hsz_per_head)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed
```

**Comment by kroggen** [comment]
The "transformers" package is not used on this repo

This repo is for inference only, not training

And it appears to be working perfectly with the original models
